### ISSUE TITLE
Checklist Funcionalidades

### ISSUE THREAD

**Issue by Sangros02** [Pablito2442/Dunder-Tifflin#7]
## Checklist Funcionalidades del Producto

- [ ] Escaparate (página de inicio)
- [ ] Registro de clientes y login
- [ ] Modificación de los datos de entrega y forma de pago para clientes registrados
- [ ] Catálogo de productos para el cliente
- [ ] Ficha de producto para el cliente (sólo consulta)
- [ ] Ficha de producto de administrador (gestión)
- [ ] Carrito de compra (cesta de compra)
- [ ] Métodos de pago: Contrareembolso y pasarela de pago
- [ ] Formas de entrega (opciones de entrega) y envío gratuito por importe
- [ ] Datos de empresa (la de la tienda)
- [ ] Gestión de ventas para el administrador
- [ ] Gestión de clientes para el administrador
- [ ] Buscador de productos por tres criterios
- [ ] Seguimiento de pedidos por ID de pedido
- [ ] Seguimiento de pedidos por el administrador
- [ ] Consulta del estado de los pedidos
